name:                cobble
version:             0.1.0.0
github:              "Innf107/cobble-compiler"
license:             BSD3
author:              "Finn Schneider"
maintainer:          "finn@famschneider.info"
copyright:           "2021 Finn Schneider"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Innf107/cobble-compiler#readme>

dependencies:
- base >= 4.7 && < 5
- relude
- directory
- text
- lens
- parsec
- polysemy
- polysemy-plugin
- filepath
- template-haskell
- zip-archive
- time
- uniplate
- containers
- cereal
- connection
- bytestring
- random
- dlist

library:
  source-dirs: src
  ghc-options:
  - -fplugin=Polysemy.Plugin
  - -Wall
  - -Werror=incomplete-patterns
  - -Wcompat
  - -Wincomplete-uni-patterns
  - -Wno-unused-imports
  - -Wno-unticked-promoted-constructors
  - -Wincomplete-record-updates
  - -Wredundant-constraints

executables:
  cobble:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cobble
    - optparse-applicative

tests:
  cobble-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cobble
    - hspec
    - process

default-extensions:
  - NoImplicitPrelude
  - ApplicativeDo
  - LambdaCase
  - OverloadedStrings
  - DataKinds
  - TypeFamilies
  - TypeFamilyDependencies
  - FlexibleInstances
  - FlexibleContexts
  - RankNTypes
  - MultiParamTypeClasses
  - PatternSynonyms
  - StandaloneDeriving
  - GADTs
  - ConstraintKinds
  - ScopedTypeVariables
  - BlockArguments
  - TypeOperators
  - NamedFieldPuns
  - MultiWayIf
  - PostfixOperators
  - KindSignatures
  - TypeApplications
  - PolyKinds
  - ViewPatterns
  - TupleSections
  - DisambiguateRecordFields
  - ImportQualifiedPost
  - NegativeLiterals
  - DeriveGeneric
  - DeriveDataTypeable
  - BangPatterns
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveTraversable
  - DerivingStrategies
  - EmptyCase
  - ExistentialQuantification
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - EmptyDataDeriving
  - RecordWildCards
  - FunctionalDependencies
